name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'


    - name: Install and run spring-javaformat
      run: |
        mvn spring-javaformat:apply
        pwd

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-jar
        path: target/*.jar

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run tests and generate Jacoco report
      run: |
        mvn spring-javaformat:apply
        mvn test verify jacoco:report

    - name: Copy Coverage To Predictable Location
      run: cp target/*/jacoco/jacoco.xml target/site/jacoco.xml

    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.3
      with:
          paths: target/site/jacoco.xml
          token: ${{ secrets.CODEGITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60

    # - name: Upload Code Coverage to GitHub
    #   uses: codecov/codecov-action@v2
    #   with:
    #     token: ${{ secrets.CODEGITHUB_TOKEN }}
    #     file: target/site/jacoco.xml
    # - name: JaCoCo Code Coverage Report
    #   id: jacoco_reporter
    #   uses: PavanMudigonda/jacoco-reporter@v5.0
    #   with:
    #       coverage_results_path: target/site/jacoco.xml
    #       coverage_report_name: Coverage
    #       coverage_report_title: JaCoCo
    #       skip_check_run: false
    #       fail_below_threshold: false
    #       publish_only_summary: false

    
          
    # - name: Archive test files and code coverage reports
    #   uses: actions/upload-artifact@v2
    #   with:
    #     path: |
    #       target/surefire-reports
    #       target/site/jacoco

    # - name: Upload code coverage
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: coverage-report
    #     path: target/site/jacoco/jacoco.xml
        
    # - name: Code Coverage Report
    #   uses: irongut/CodeCoverageSummary@v1.3.0
    #   with:
    #     filename: target/site/jacoco/jacoco.xml
    #     badge: true
    #     fail_below_min: true
    #     format: markdown
    #     hide_branch_rate: false
    #     hide_complexity: true
    #     indicators: true
    #     output: both
    #     thresholds: '60 80'

  docker-build:
    runs-on: ubuntu-latest
    needs: build
    

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download JAR artifact
      uses: actions/download-artifact@v2
      with:
        name: app-jar
        path: target/*.jar

    - name: docker login
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ruth99/github-actions-pet-clinic:${{ github.sha }}
          
        

  
