name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'


    - name: Install and run spring-javaformat
      run: |
        mvn spring-javaformat:apply

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-jar
        path: target/*.jar

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run tests and generate Jacoco report
      run: |
        mvn spring-javaformat:apply
        mvn test verify jacoco:report
        
    - name: Archive test files and code coverage reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: |
          target/surefire-reports
          target/site/jacoco

    # - name: Upload code coverage
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: coverage-report
    #     path: target/site/jacoco/jacoco.xml
        
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: site/jacoco/jacoco.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

  docker-build:
    runs-on: ubuntu-latest
    needs: build
    

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download JAR artifact
      uses: actions/download-artifact@v2
      with:
        name: app-jar
        path: target/*.jar

    - name: docker login
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ruth99/github-actions-pet-clinic:${{ github.sha }}
          
        

  
